app/assets/javascripts/user_profiles.js
app/assets/stylesheets/scaffolds.scss
app/assets/stylesheets/user_profiles.scss
app/controllers/user_profiles_controller.rb
app/helpers/user_profiles_helper.rb
app/models/user_profile.rb
app/views/user_profiles/_form.html.erb
app/views/user_profiles/_user_profile.json.jbuilder
app/views/user_profiles/edit.html.erb
app/views/user_profiles/index.html.erb
app/views/user_profiles/index.json.jbuilder
app/views/user_profiles/new.html.erb
app/views/user_profiles/show.html.erb
app/views/user_profiles/show.json.jbuilder
config/routes.rb
db/migrate/20191111084536_create_user_profiles.rb
db/schema.rb
test/controllers/user_profiles_controller_test.rb
test/fixtures/user_profiles.yml
test/models/user_profile_test.rb
test/system/user_profiles_test.rb

I've added the model, controller and view for user_profile

Add scaffold for user_profile

---

app/controllers/registrations_controller.rb
config/routes.rb

Enable redirect of user and vet to their respective create new profile page after registration.

Redirect route for registration

---

app/assets/javascripts/pets.js
app/assets/stylesheets/pets.scss
app/controllers/pets_controller.rb
app/helpers/pets_helper.rb
app/models/pet.rb
app/views/pets/_form.html.erb
app/views/pets/_pet.json.jbuilder
app/views/pets/edit.html.erb
app/views/pets/index.html.erb
app/views/pets/index.json.jbuilder
app/views/pets/new.html.erb
app/views/pets/show.html.erb
app/views/pets/show.json.jbuilder
config/routes.rb
db/migrate/20191111153404_create_pets.rb
db/schema.rb
test/controllers/pets_controller_test.rb
test/fixtures/pets.yml
test/models/pet_test.rb
test/system/pets_test.rb

I've generated the MVC for pets using scaffold.

Create scaffold for pets

---

app/models/user.rb
app/models/vet.rb
db/migrate/20191112013548_users_vets.rb
db/schema.rb

Add users_vets join table

---

app/controllers/user_profiles_controller.rb
app/controllers/vet_profiles_controller.rb
app/views/user_profiles/show.html.erb

I've updated the user profile page `/user_profiles/:id`:
1. Show a list of user's `pets`
2. Show a list of user's vets (showing the `vet_profiles`)
3. `vet_profile` (`\vet_profiles` and `\vet_profiles\:id`)is made accessible for users

Update user profile

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb

Please bundle install for bootstrap

Add bootstrap and navbar

---

app/controllers/vet_profiles_controller.rb
app/views/vet_profiles/show.html.erb
config/routes.rb

1. add a new controller action `add_vet_to_pet`
2. add a new `POST` route `/vet_profiles/:id/add_vet_to_user`
3. when `add as vet` is clicked, the join table `users_vets` will be updated

Add vet to user

---

app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb

Add in jumbotron container
Updated navbar
Add footer

Update views for sign_up and sign_in

---

app/models/user_profile.rb
app/views/user_profiles/_form.html.erb
app/views/user_profiles/index.html.erb
app/views/user_profiles/show.html.erb
app/views/vet_profiles/index.html.erb
db/seeds.rb

Add image upload for user profile

Add rails storage

---

.gitignore
Gemfile
Gemfile.lock
config/environments/development.rb

How to make this to work:
1) bundle install
2) touch .env
3) Edit the .env file, this will not be uploaded to github
GMAIL_USERNAME = your_throw_away_gmail_account_without_quotes
GMAIL_PASSWORD = your_throw_away_gmail_password_without_quotes

Fixed reset password mailer

---

config/environments/production.rb

Basic settings are added. Will need to update this when we get our heroku url

Added reset password mailer settings for production

---

app/views/user_profiles/_form.html.erb
app/views/user_profiles/edit.html.erb

add css to edit user profile form

Show display pic and display pic file name

---

app/views/pets/show.html.erb

Add boostrap to show pet profile

---

app/views/pets/_form.html.erb
app/views/pets/edit.html.erb

add bootstrap to `view` for `pets\:id\edit`

Add bootstrap to edit pet profile

---

Gemfile
Gemfile.lock
app/controllers/vet_profiles_controller.rb
app/views/vet_profiles/index.html.erb
app/views/vet_profiles/show.html.erb
db/seeds.rb

Enable geocode location for Vet profile page
db seeds have been rewritten, please drop your database

Add geocode

---

app/controllers/pet_records_controller.rb
app/views/pet_records/_form.html.erb
app/views/pet_records/edit.html.erb
app/views/pet_records/show.html.erb

Show and edit pet record

---

app/views/home/index.html.erb
app/views/vet_profiles/index.html.erb

Bootstrap vet profiles index
Amended CSS of homepage, but yet to adjust for carousel images mobile responsiveness

Layout vet profile index

---

app/controllers/vet_profiles_controller.rb
db/migrate/20191113094154_add_country_and_website_url.rb
db/migrate/20191113100041_add_country_and_postal_code_to_user_profile.rb
db/schema.rb
db/seeds.rb

Modified seeds, please drop database and re-seed

Add geocode to vet profiles

---

app/views/pets/_form.html.erb

Fix date select at edit pet profile

---

app/controllers/pet_records_controller.rb
app/controllers/pets_controller.rb
app/views/pet_records/new.html.erb
app/views/pet_records/show.html.erb
app/views/pets/show.html.erb

Update pet profile with ability to CRUD pet records

Update pet profile

---

app/controllers/pets_controller.rb
app/models/pet.rb
app/views/pets/show.html.erb
app/views/user_profiles/show.html.erb

- button to add pet
- button to remove pet at pet card in user profile
- button to remove pet at pet profile
- when pet is removed, all the pet's pet records are also removed

Add pet at user profile

---

Gemfile
Gemfile.lock
app/controllers/vet_profiles_controller.rb
app/models/vet_profile.rb
app/views/user_profiles/_results.html.erb
app/views/user_profiles/_search-results.js.erb
app/views/user_profiles/show.html.erb

At user profile, add:
1. Search bar for AJAX searching of vets
2. Button to add vet to user when vet is found

Enable searching of vets and add vet to user

---

app/controllers/vet_profiles_controller.rb
app/views/user_profiles/show.html.erb
config/routes.rb

I've added:
1. a new controller action `remove_vet_from_user` at `vet_profiles_controllers` to remove a vet from a user's list of vets
2. a button at `show.html.erb` at `views\vet_profiles` at the vet's card
3. a new POST route for `remove_vet_from_user`

Enable removal of a vet from a user

---

app/assets/stylesheets/application.scss
app/controllers/home_controller.rb
app/views/user_profiles/show.html.erb
app/views/vet_profiles/index.html.erb
app/views/vet_profiles/show.html.erb

Also added media query
Amended vet_profiles index to:
- Remove services
- Show Add Vet button only when user sign_in

Layout vet profile

---

app/models/vet.rb
app/views/user_profiles/_results.html.erb

show `added` when the vet is already added

Add logic to search vet results

---

app/models/vet.rb
app/views/vet_profiles/index.html.erb
app/views/vet_profiles/show.html.erb

add conditional logic for showing add vet button

Show remove vet button at vet profile

---

app/views/user_profiles/_form.html.erb
app/views/user_profiles/new.html.erb

1. moved profile pic to the top
2. default svg file not resized yet

Move profile pic to the top

---

app/controllers/home_controller.rb
app/views/layouts/_navbar.html.erb
app/views/layouts/_results.html.erb
app/views/layouts/_search-results.js.erb
app/views/layouts/application.html.erb

the search bar of navbar is now usable

Enable search bar of navbar

---

app/models/vet_profile.rb

now we can search by address, postcode or clinic name, for the search bar at navbar and also the search bar at user profile page.

Search vet by address, postcode or clinic name

---

app/views/pets/_form.html.erb
app/views/pets/new.html.erb
app/views/user_profiles/_form.html.erb

Show preview of profile pet and user image

---

Gemfile
Gemfile.lock
app/assets/javascripts/contacts.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/contacts.scss
app/controllers/contacts_controller.rb
app/helpers/contacts_helper.rb
app/models/contact.rb
app/views/contacts/create.html.erb
app/views/contacts/new.html.erb
config/routes.rb
test/controllers/contacts_controller_test.rb

Need to utilize it at the correct location

Add contact form to vet

---

app/views/pets/_form.html.erb
app/views/user_profiles/show.html.erb
app/views/vet_profiles/show.html.erb

Fix margin top and bottom for containers

---

app/controllers/vet_profiles_controller.rb
app/views/vet_profiles/show.html.erb
db/migrate/20191116105508_add_popup_hash.rb
db/schema.rb
db/seeds.rb

Brute force method to display markers by distance.
This including caching.

Add clinic name to popup in map

---

app/controllers/vet_profiles_controller.rb
app/views/vet_profiles/index.html.erb
db/schema.rb

only works when user is NOT logged in

Show searched vets (only when logged out)

---

app/views/home/index.html.erb
app/views/vet_profiles/index.html.erb

Users can set and display distance with the range

Add distance range ui

---

app/controllers/pet_records_controller.rb
app/controllers/pets_controller.rb
app/controllers/vet_profiles_controller.rb
app/controllers/vets_controller.rb
app/models/user.rb
app/views/home/index.html.erb
app/views/pet_records/show.html.erb
app/views/pets/show.html.erb
app/views/vet_profiles/_form.html.erb
app/views/vet_profiles/edit.html.erb
app/views/vets/show.html.erb

- Fix carousel links
- Updated edit vet profile form to correct vet update error
- Updated vet dashboard to display by pets
- Updated user model to chain to user profile
- Updated pet & pet profile show pages to allow show view

Updated some stuff

---

app/controllers/pets_controller.rb
app/views/pet_records/show.html.erb
app/views/pets/show.html.erb
app/views/user_profiles/show.html.erb

Auto close alerts

---

app/views/vet_profiles/index.html.erb
db/migrate/20191118060205_add_emergency_to_vet_profile.rb
db/schema.rb
db/seeds.rb

add `24-hour` badges to clinics with 24-hour emergency services

Update clinics with 24 hour service

---

app/assets/stylesheets/application.scss
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/home/index.html.erb
app/views/pets/show.html.erb
app/views/user_profiles/show.html.erb
app/views/vet_profiles/index.html.erb
app/views/vets/show.html.erb

Standardize buttons and text color

Match style across pages

---

app/controllers/vet_profiles_controller.rb
app/views/vet_profiles/index.html.erb

Add 24 hr vet filter

---

app/views/pets/show.html.erb

Correct pet name to text-white

Amend columns for show pet page
